'your account details' api
Wo-m/tickexperience-backend pull request #12
Opened 2023-09-01 06:45 UTC by hcmgr

implemented an /api/authed/user/details endpoint that returns user details. Also implemented a RegisterDTO for the AuthService

2023-09-01 06:51 UTC, Wo-m requested changes

2023-09-01 06:51 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/service/AuthService.java
> +    public TokenDTO register(RegisterDTO registerDTO) {
Probably don't need the function overload, I can't see an instance where we register a user outside of the api endpoint with the DTO

2023-09-01 06:51 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/service/AuthService.java
> +        // NOTE: newly registered user needs token too
Nah, usual flow for registration it's register and then login. because you'd have an email validation or something like that in between. So just void return

2023-09-01 06:51 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/service/UserService.java
> +    // NOTE: simply returning 'User' will serialise all fields we need
Don't need this, just a spring thing not a special case

2023-09-01 06:51 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/model/entity/User.java
> +    // NOTE: no JsonIgnore here IS INTENTIONAL (ask Rack)
hmm?

2023-09-01 06:56 UTC, hcmgr commented on src/main/java/com/deco/tickexperience/model/entity/User.java
> +    // NOTE: no JsonIgnore here IS INTENTIONAL (ask Rack)
its a password hash, not a password, so it's perfectly secure to pass it to the front-end. We want to pass this to the front-end in cases where, for instance, they want to change their password

2023-09-01 06:56 UTC, hcmgr commented on src/main/java/com/deco/tickexperience/service/AuthService.java
> +    public TokenDTO register(RegisterDTO registerDTO) {
ye aight

2023-09-01 06:56 UTC, hcmgr commented on src/main/java/com/deco/tickexperience/service/AuthService.java
> +        // NOTE: newly registered user needs token too
ye aight

2023-09-01 06:56 UTC, hcmgr commented on src/main/java/com/deco/tickexperience/service/UserService.java
> +    // NOTE: simply returning 'User' will serialise all fields we need
don't need the comment? or don't the entire method?

2023-09-01 06:57 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/service/UserService.java
> +    // NOTE: simply returning 'User' will serialise all fields we need
the comment

2023-09-01 07:02 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/model/entity/User.java
> +    // NOTE: no JsonIgnore here IS INTENTIONAL (ask Rack)
Why would we need to pass the hash the front end if they want to change their password? I imagine that would be achieved by sending a combo of old pw and new pw to backend, verifying the old pw and setting the new pw. 

Regardless sending a hashed pw around doesn't make any sense because its purposely hashed so that it has no usefulness it the hashed form.

Even though its secure, still better kept hidden.

2023-09-01 07:05 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/controller/AuthController.java
> +    public void register(@RequestBody final RegisterDTO registerDTO) { authService.register(registerDTO); }
please dont do one liners like this, i know its pedantic but hard to read

2023-09-02 05:38 UTC, Wo-m approved these changes
grumble

2023-09-02 05:38 UTC, merged