wired up video urls
Wo-m/tickexperience-backend pull request #38
Opened 2023-10-17 08:15 UTC by hcmgr

2023-10-17 21:41 UTC, Wo-m requested changes

2023-10-17 21:41 UTC, Wo-m commented on src/main/java/com/deco/tickexperience/model/entity/Sport.java
> +import jakarta.persistence.*;
I imagine your ide did this, by default i think if you import >=5 from a package it does a insert all. Can change it somewhere

2023-10-17 21:41 UTC, Wo-m commented on src/main/resources/db/changelog/mock_events.sql
> +INSERT INTO Event (SportId, VenueId, Name, StartTime, EndTime, ImageURL, Gender) VALUES (3, 2, 'Finals Rounds', '2032-08-07T11:00:00', '2032-08-07T14:00:00', 'https://images.unsplash.com/photo-165067
This was on purpose, have the finals at a different venue. I believe 3 is the gabba and 2 is suncorp so both capable of hosting a football match.

2023-10-18 01:47 UTC, hcmgr commented on src/main/resources/db/changelog/mock_events.sql
> +INSERT INTO Event (SportId, VenueId, Name, StartTime, EndTime, ImageURL, Gender) VALUES (3, 2, 'Finals Rounds', '2032-08-07T11:00:00', '2032-08-07T14:00:00', 'https://images.unsplash.com/photo-165067
oh soooooooo

2023-10-18 01:48 UTC, hcmgr commented on src/main/java/com/deco/tickexperience/model/entity/Sport.java
> +import jakarta.persistence.*;
REMOVING IT FUCKS IT, 'LLOW IT LAD

2023-10-18 05:07 UTC, Wo-m approved these changes

2023-10-18 05:07 UTC, merged